version: "3.9"

services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: telegram_bot_news_bot
    restart: always
    command: python3 main.py
    depends_on:
      - redis
  redis:
    image: redis:5-alpine
    container_name: telegram_bot_news_redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
  postgres:
    image: postgres:15
    container_name: telegram_bot_news_postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./telegram_bot_news_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5